version: v34.10.1
files:
  - .github/workflows/codeql-analysis.yaml
  - .github/workflows/close-stale-prs.yaml
  - .github/workflows/pr-help.yaml
  - .github/workflows/renovate_dependency_management.yaml
values:
  runWizCliDepsScan: false
  renovateCronjobSchedule: "55 7 * * 1-5" # This is UTC -> At 08:55 CET / 09:55 CEST on every day-of-week from Monday through Friday.
