name: 'Post preview URLs'
description:
    'Append the URLs for branch app and storybook preview deployments to the PR description.'
author: 'Pleo'
inputs:
    token:
        description: GitHub token used to update the PR description
        required: false
        default: ${{ github.token }}
    links:
        description:
            'JSON specification of links to post to the PR description (`Array<{name: string, url:
            string}>`)'
        required: true
    as_labels:
        description:
            If true, the URL is not displayed and all links are rendered as a comma-separated list
        required: false
        default: 'false'
    app_name:
        description: The name displayed in the link section title
        required: false
        default: 🤖 App
runs:
    using: 'node16'
    main: 'dist/main/index.js'
