name: "PR Check"

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  semantic-title:
    name: Check PR Title for Semantic Release Type
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: read
    steps:
      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v3.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
