name: Pull Request Check
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semantic-title:
    name: Check PR Title for Semantic Release Type
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: read
    steps:
      - name: Check PR Title
        if: github.event_name == 'pull_request'
        uses: amannn/action-semantic-pull-request@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true

  check-workflow:
    name: Check reusable workflow
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4.1.4
      - run: |
          for file in reusable-workflows/*.yml; do
            filename=$(basename $file)
            cmp --silent .github/workflows/$filename $file || (echo "::error::When editing reusable workflows, update both \`reusable-workflows\` and \`.github/workflows\` for file: $filename" && exit 1)
          done

  test-actions:
    name: Check actions
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: actions
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: actions/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: make test
      - run: make lint
      - run: make build

      - name: Check if built version was committed
        run: |
          git diff --exit-code || (echo "::error::You forgot to commit the built actions, run 'make' locally" && exit 1)

  test-lambdas:
    name: Check Lambda@Edge Functions
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: terraform-module/edge-lambdas
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: terraform-module/edge-lambdas/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: make test
      - run: make lint
      - run: make build

      - name: Check if built version was committed
        run: |
          git diff --exit-code || (echo "::error::You forgot to commit the built actions, run 'make' locally" && exit 1)

  test-config:
    name: Check config
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: config-inject
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: config-inject/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm run build
      - run: pnpm run test
      - run: pnpm run lint
      - run: pnpm run typecheck
